name: Testing here
on: push
jobs:
    Setting_up_server:
         runs-on: ubuntu-latest
         steps:
         - name: Creating folder
           run: |
               sudo mkdir Action
               cd Action
               touch file1.txt 
               "ACTION FOLDER WITH FILE1" >>file1.txt

            
                
         