name: Testing here
on: 
   push: 
        paths-ignore:
            - index.yml
   
jobs:
    Setting_up_server:
         runs-on: ubuntu-latest
         steps:
         - name: Creating folder
           run: |
               sudo mkdir Action
               cd Action
               sudo touch file1.txt
               sudo chmod 777 file1.txt
               echo "ACTION FOLDER WITH FILE1" >>file1.txt
               cat file1.txt

            
                
         