name: Testing here
on: 
   push: 
        paths-ignore:
            - .github/workflows/index.yml   
        #paths:
        #   - .github/workflows/testing.yml
        
jobs:
    Setting_up_server:
         runs-on: ubuntu-latest
         steps:
         - name: Creating folder and Creating file and giving permisiions and Adding text and printing
           run: |
               sudo mkdir Action
               cd Action
               sudo touch file1.txt
               sudo chmod 777 file1.txt
               echo "ACTION FOLDER WITH FILE1" >>file1.txt
               cat file1.txt
               pwd
         - name: Uploading the data in instance
           uses: actions/upload-artifact@v4
           with:
              name: Action folder
              path: Action

    Checking_again:
         needs: Setting_up_server
         runs-on: ubuntu-latest
         steps:
         - name: Downloading folder from instance
           uses: actions/download-artifact@v4
           with:
             name: Action folder
         - name: Checking the previous data
           run: |
              cd Action
              cat file1.txt

            
                
         